DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS events;

CREATE TABLE user (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username NVARCHAR(100) UNIQUE NOT NULL,
    Password NVARCHAR(100) NOT NULL
);

CREATE TABLE events (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Event_Name NVARCHAR(255) NOT NULL,
    Event_Date DATETIME NOT NULL,
    Event_Type NVARCHAR(255) NULL,
    Missing_Friends NVARCHAR(255) NULL,
    CreateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);